# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker build -t $(imageName):$(Build.BuildId) -t $(imageName):latest .
  displayName: 'docker build'
- script: |
    docker tag $(dockerId).azurecr.io/$(imageName):$(Build.BuildId)
    docker tag $(dockerId).azurecr.io/$(imageName):latest
  displayName: 'docker tag images'
- script: |
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io 
    docker push $(dockerId).azurecr.io/$(imageName):$(Build.BuildId)
    docker push $(dockerId).azurecr.io/$(imageName):latest
  displayName: 'docker login and push'
